### ISSUE TITLE
German umlauts in data source file lead to error

### ISSUE THREAD

**Issue by lino** [jhpyle/docassemble#142]
I declare Organizations either in an input file or in the interview file itself using german Umlauts.

My data source file looks like this

    # ministerien.yml
    object: Organization
    module: docassemble.base.util
    items:
      - name: Bundesministerium der Finanzen
        shorthand: BMF
        address:
          addresss: Wilhelmstraße 97
          zip: 10117
          city: Berlin
          country: DE
      - name: Auswärtiges Amt
        shorthand: AA
        address:
          address: Werderscher Markt 1
          zip: 10117
          city: Berlin
          country: DE

When i import the data using objects from file and create a question which asks for a single object from the list

    # interview file
    ...
    ---
    objects from file:
      - ministerien: ministerien.yml
    ...
    ---
    mandatory: True
    field: gegenpartei
    question: |
      Gegen welches Ministerium streben Sie das Verfahren an?
    datatype: object
    dropdown:
      code: |
        ministerien

I get an error

    Failure while processing field with datatype of object: 'utf-8' codec can't decode byte 0xe9 in 
    position 1: invalid continuation byte

The file is valid UTF-8, i'd guess something gets converted during the upload.

**Comment by jhpyle** [comment]
You can't use `datatype` outside of an item in a list of `fields`.  This should work:

```
mandatory: True
question: |
  Gegen welches Ministerium streben Sie das Verfahren an?
fields:
  - no label: gegenpartei
    datatype: object
    choices:
      - ministerien
```

I think the error arose because it was ignoring `datatype: object` and was treating the list of objects like a list of text strings.

By the way, your addresses are coming through as plain Python dictionaries.  You need to explicitly say that the address is an object.  I have some code that converts the `name` into an object, but I don't have code for every attribute that is an object.

```
object: Organization
module: docassemble.base.util
items:
  - name: Bundesministerium der Finanzen
    shorthand: BMF
    address:
      object: Address
      module: docassemble.base.util
      item:
        address: Wilhelmstraße 97
        zip: 10117
        city: Berlin
        country: DE
  - name: Auswärtiges Amt
    shorthand: AA
    address:
      object: Address
      module: docassemble.base.util
      item:
        address: Werderscher Markt 1
        zip: 10117
        city: Berlin
        country: DE
```
