### ISSUE TITLE
File upload field not recognising correct filetype with 'accept' specifier

### ISSUE THREAD

**Issue by lordenaar** [jhpyle/docassemble#149]
When using the 'accept' specifier in a file upload field, the browser recognises the accepted file extension, and other extensions are not permitted to be selected. When a correct filetype is selected, "Please upload a file with a valid file format." is displayed upon pressing continue.

The following question demonstrates the error (for DRF files):
```
mandatory: true
question: Upload a .drf file
fields:
  - File: new_file
    datatype: file
    accept: |
      '.drf'
---
```
Giving a single string specifier as per the Mozilla page referenced in the DA documentation:

> A valid case-insensitive filename extension, starting with a period (".") character. For example: .jpg, .pdf, or .doc.

Using Google Chrome Version 73.0.3683.103 (64 bit)
