### ISSUE TITLE
Regression: Field saves variable name instead of variable value 

### ISSUE THREAD

**Issue by houfu** [jhpyle/docassemble#168]
Quickest yml reproduce:
```yml
question: |
  Enter a name of a fruit and vegetable.
subquestion: |
  Please be specific.
fields:
  - Vegetable: vegetable_variable
  - Fruit: fruit_variable
---
question: |
  Which fruit/vegetable do you like the most?
field: favourite_thing
choices:
  - ${vegetable_variable}
  - ${fruit_variable}
---
mandatory: true
question: |
  You chose ${favourite_thing}
```

**What I expected**: If I had entered "Carrot" for vegetable in question 1, and then chosen a vegetable in question 2, I expected the mandatory question to say `You chose Carrot`. 
**What I got instead**: Mandatory question says `You chose ${vegetable_variable}`

**Notes**
- In question 2, the choices came out as variable values as expected.
- Based on the debug source and variables, "${vegetable_variable}" is saved as plain text.
![Screenshot 2019-07-11 at 10 11 43 AM](https://user-images.githubusercontent.com/19525701/61017028-59fa3c80-a3c4-11e9-8576-ddb4bf4519e9.png)
- I do not monitor releases closely (sorry!), but this worked on docassemble 0.4.38 and the last version of docassemble I have that produces this issue is 0.4.58. 0.4.60 does not fix this.
