### ISSUE TITLE
Nested show if fields occasionally fails to trigger

### ISSUE THREAD

**Issue by staffanm** [jhpyle/docassemble#375]
(Tested on  1.2.41 in a docker deployment.) This interview has three fields of different types. The last field is always shown, even if I change the answer to the second field. If I remove the help text from the one choice, it works as expected.

```yaml
mandatory: true
question: Test
fields: 
  - Main question: main
    datatype: yesnoradio
    default: true
    
  - Follow-up question: followup
    input type: radio
    default: additional
    choices:
      - Require additional follow-up: additional
        help: This presence of this help text triggers the issue
      - Don't: dont
    show if: main

  - 2nd level follow-up: belopp
    show if:
      variable: followup
      is: additional
    # js show if: |
    #   val("followup") == "additional"
```

If I use a `js show if` for the last field instead (commented out in the above example), the problem is sort of reversed: The last field is not shown on page load, even if it should be. Toggling the answer to the second question back and forth shows the field, though.

Unfortunately, I haven't been able to debug the JS code, possibly because it is inline and my browsers developer tools won't reliably set a breakpoint in them.
