### ISSUE TITLE
uncheck other does not cause the field to act exactly like a "none of the above" field

### ISSUE THREAD

**Issue by staffanm** [jhpyle/docassemble#407]
The documentation for [uncheck others](https://docassemble.org/docs/fields.html#fields%20yesno) states that this modifier will cause the field to act as a “none of the above” field for other yes/no checkbox fields. However, there is a small difference in behavior between a regular none of the above choice and a yesno field with this modifier. With the following test interview:

```yaml
mandatory: true
question: Uncheck others
fields:
  - Regular checkboxes: check
    datatype: checkboxes
    choices:
      - one
      - two
  - note: Yes/no-fields with uncheck others
  - one: one 
    datatype: yesno
  - two: two
    datatype: yesno
  - none of the above: other
    datatype: yesno
    uncheck others:
      - one
      - two
```

If the user checks "none of the above" it clears all other choices for both cases. But if the user **then** selects any of the other choices, the regular checkbox field will clear the `none of the above` choice, but the set of yes/no fields will not clear the corresponding  `none of the above` field. This makes it possible for the user to submit an answer with both "one", "two" and "none of the above", which is not possible with regular checkboxes.
