### ISSUE TITLE
Filling pdf with signature not working

### ISSUE THREAD

**Issue by ykorzikowski** [jhpyle/docassemble#434]
Signature stays empty

Not working version: current - 1.2.88
last working version: 1.2.71

```
metadata:
  title: Tecis
  short title: TFP
  comment: This is a learning tool.  Feel free to write over it.
---
objects:
  - client: Individual
  - photographer: Individual
  - shooting: Individual
---
mandatory: True
code: |
  multi_user = True
  photographer.name = "Yannik Korzikowski"
  authority = "****@***.de"
---
question: |
  Was ist deine Adresse?
fields:
  - Name: client.name
  - Adresse: client.address
  - PLZ und Stadt: client.city
  - E-Mail: client.mail
mandatory: true
---
question: |
  Unterschrift Fotograf
signature: photographer.signature
under: |
  ${ photographer }
mandatory: true

---
question: |
  Unterschrift Kunde
subquestion: |
  Link: [teilen](${ interview_url() })
signature: client.signature
under: |
  ${ client }
mandatory: true
---
code: |
   mail_me = send_email(to=[authority, client.mail], attachments=[tecis_file])
mandatory: true
---
sets: final_screen
question: Here is your document.
buttons:
  - MailMe: mail_me
attachment:
  - name: tecis
    filename: tecis.pdf
    event: mail_me
    pdf template file: tecis.pdf
    variable name: tecis_file
    editable: False
    fields:
      - "name": ${ client.name }
      - "addr_1": ${ client.address }
      - "addr_2": ${ client.city }
      - "date": 16.07.2021
      - "sign_client": |
          ${ client.signature }
      - "sign_photo": |
          ${ photographer.signature }
mandatory: true
---
```

PDF atached
