### ISSUE TITLE
show if doesn't work if labels above fields is True (but js show if works)

### ISSUE THREAD

**Issue by staffanm** [jhpyle/docassemble#501]
With the following interview:

```yaml
features:
  labels above fields: True
---
mandatory: True
question: Q
fields:
  - Main question: m
    datatype: yesno
  - Subquestion: s
    show if: m
```

the subquestion is never shown. However, if `labels above fields` is set to False, or the `show if` directive is changed to the equivalent `js show if` directive, it gets shown.

Not sure when this appeared, but probably somewhere around the Bootstrap 4 -> 5 upgrade.
