### ISSUE TITLE
Scrollable list of projects

### ISSUE THREAD

**Issue by nonprofittechy** [jhpyle/docassemble#509]
When you have a very long list of projects in your playground, there is no way to either access the bottom-most project or to edit and cleanup your long list of projects, other than resizing all of the text on screen.

Suggestion: use overflow: scroll when someone has a long list. It may also make sense to put the "manage projects" link on top of the list.

This CSS should work:

```css
.dropdown-menu {
  overflow-y: auto;
  height: 90vh;
}
```
