### ISSUE TITLE
include_docx_template may create numbering for paragraph-styled cells in included tables

### ISSUE THREAD

**Issue by staffanm** [jhpyle/docassemble#574]
Under very specific circumstances, include_docx_template may change an included table in such a way that the first cell of the table gets numbered, even though the included document has no such numbering.

Given the following interview
```yaml
question: composed docx
attachments:
  - name: composed
    docx template file: master.docx
    valid formats:
      - docx
mandatory: True
```

And these docx template files:

- [master.docx](https://github.com/jhpyle/docassemble/files/9675610/master.docx)
- [sub.docx](https://github.com/jhpyle/docassemble/files/9675611/sub.docx)

The included file, which should look like:
![Skärmbild 2022-09-29 163846](https://user-images.githubusercontent.com/4435171/193061603-556f79f3-4fbc-472e-8fd8-beb83ff33472.png)

instead looks like this in the finished document:
![Skärmbild 2022-09-29 163916](https://user-images.githubusercontent.com/4435171/193061623-57d0519a-7f47-4262-aa53-54f21bf1dc42.png)

The bug only manifests under very specific circumstances:
* there must be a top-level table in the included file
*  that in its first cell has a non-outline paragraph style applied, and
*  a subsequent table cell that contains a numbered element with a named paragraph style applied

I think I've located the root cause and will submit a PR shortly.
