### ISSUE TITLE
Javascript validator for CustomDataType fails if fields are defined by code

### ISSUE THREAD

**Issue by staffanm** [jhpyle/docassemble#588]
Given the `SSN` CustomDataType given [in the documentation](https://docassemble.org/docs/fields.html#custom%20datatype), the following interview, which defines a fields of that type in code, fails when validating an invalid input:

```yaml
modules:
 - .ssn
---
mandatory: true
question: custom js validator
fields:
  - code: |
      [{"SSN 1": "ssn1", "datatype": "ssn"}]
  #- SSN 2: ssn2
  #  datatype: ssn

```

No error messages are shown for invalid input, and regardless of whether the input is valid or not, the following stack trace is shown in the browser developer console:
```
index.js:83 Uncaught TypeError: Cannot read properties of undefined (reading 'call').  Exception occurred when checking element c3NuMg, check the 'ssn' method.
    at a.validator.check (index.js:83:17)
    at a.validator.element (index.js:83:17)
    at a.validator.onfocusout (index.js:83:17)
    at a.validator.<anonymous> (VM21 interview:1082:26)
    at HTMLInputElement.b (index.js:83:17)
    at HTMLFormElement.dispatch (bundle.js?v=1.4.18:2:43064)
    at v.handle (bundle.js?v=1.4.18:2:41048)
    at Object.trigger (bundle.js?v=1.4.18:2:71515)
    at Object.simulate (bundle.js?v=1.4.18:2:72018)
    at HTMLDocument.i (bundle.js?v=1.4.18:2:72307)
```

However, if another field with the same datatype is present and not defined in code (eg by uncommenting lines in the above example), validation succeds as expected without errors. Maybe the javascript that adds the jquery-validation rule is not included when defining fields in code?
