### ISSUE TITLE
show if and disable if on the same field behaves unexpectedly

### ISSUE THREAD

**Issue by staffanm** [jhpyle/docassemble#691]
Given the following interview:
```yaml
question: disable
mandatory: true
fields:
  - A: a
    datatype: yesno
  - B: b
    datatype: yesno
  - C: c
    datatype: yesno
    show if: b
    disable if: a
```

The field c is always shown, regardless of whether B is true or false. If the options for C appear in different order, so that `disable if` comes before `show if`, it is shown only when B is true, but then it is never disabled regardless of whether A is true or false.

If either option is exchanged to its js counterpart (eg `js show if: val("b")`) it works like expected, but only if A and B is checked in a specific order.
