### ISSUE TITLE
Interview datatype date is returning 'Bad date' in the downloded document

### ISSUE THREAD

**Issue by guidupas** [jhpyle/docassemble#756]
I have created an interview with a field defined as date datatype. When I download my document it has a 'Bad date' where the date should be.

![Screenshot from 2024-03-19 14-11-07](https://github.com/jhpyle/docassemble/assets/12818273/d4239d08-5d3b-402a-b3a1-ffc2182de87c)
![Screenshot from 2024-03-19 14-11-37](https://github.com/jhpyle/docassemble/assets/12818273/bbb5c673-3c21-462f-a273-76fbac2c4713)

**Comment by jhpyle** [comment]
I attempted to reproduce this issue with the following interview. I did not get a "Bad date" problem.
```
mandatory: True
question: Your document
attachment:
  docx template file: testdate.docx
---
question: |
  Date
fields:
  - Date: some_date
    datatype: date
```
Here is the document: [testdate.docx](https://github.com/jhpyle/docassemble/files/14654961/testdate.docx)

I will need more information such as your interview YAML and the document you are trying to assemble.
