### ISSUE TITLE
One cannot add DADict items to a table with `show incomplete`

### ISSUE THREAD

**Issue by fkohrt** [jhpyle/docassemble#808]
If I try to add items using an editable table to a DADict, this fails if `show incomplete` is enabled. It does work with a table populated by a DAList, so I'm suspecting this is a bug.

```yml
---
objects:
  - income: DADict.using(object_type = DAObject)
---
table: income.table
rows: income
show incomplete: true
columns:
  - Type: row_index
  - A: row_item.a
  - B: row_item.b
edit:
  - a
  - b
---
event: review_table
question: |
  Summary of income
review:
  - note: |
      ${ income.table }
    
      ${ income.add_action() }
continue button field: show_review_screen
skip undefined: False
---
question: |
  Add another income?
yesno: income.there_is_another
---
question: |
  Income name?
fields:
  - Income: income.new_item_name
---
question: |
  A?
yesno: income[i].a
---
question: |
  B?
fields:
  - B: income[i].b
    datatype: number
---
question: |
  Any?
yesno: income.there_are_any
---
mandatory: True
question: Test
subquestion: |
  [Review your answers](${ url_action('review_table')})
```
