### ISSUE TITLE
Interaction with table of DADict items seeks `.there_is_another`

### ISSUE THREAD

**Issue by fkohrt** [jhpyle/docassemble#809]
Given the following table populated by a DADict, whatever action I take, Docassemble seeks `income.there_is_another`. This is only resolved by adding a mandatory code block with `income.there_is_another = False`.

I have not found that to be the case for prepopulated DAList in a table, so I suspect this might be a bug.

```yml
metadata:
  title: Table for dictionary
---
variable name: "income"
data:
  employment:
    object: DAObject
    module: docassemble.base.util
    item:
      a: True
      b: 10
  business:
    object: DAObject
    module: docassemble.base.util
    item:
      a: True
      b: 10
  recreation:
    object: DAObject
    module: docassemble.base.util
    item:
      a: True
      b: 10
use objects: objects
gathered: True
---
code: |
  income.set_object_type(DAObject)
mandatory: True
---
table: income.table
rows: income
columns:
  - Type: row_index
  - A: row_item.a
edit:
  - a
---
mandatory: True
question: |
  Summary of income
subquestion: |
  ${ income.table }
  
  ${ income.add_action() }
---
question: |
  Add another income?
yesno: income.there_is_another
---
question: |
  Income name?
fields:
  - Income: income.new_item_name
---
question: |
  A?
yesno: income[i].a
---
```

**Comment by jhpyle** [comment]
The `DAObject` is a base class. It is not intended to be used directly. It can be used directly, but it too featureless to be convenient.

With a plain `DAObject` you need to set `complete_attribute` and write a `code` block that specifies what you want collected for each item. The logic of the `table` buttons requires these rules to be specified.

```
mandatory: True
code: |
  income.object_type = DAObject
  income.complete_attribute = 'complete'
---
code: |
  income[i].a
  income[i].complete = True
```
See

**Comment by fkohrt** [comment]
I see! I've been avoiding `Thing` because it requires a name and the things I wanted to record did not always have one. Bit I'll use `Thing` then.

**Comment by fkohrt** [comment]
Hm, I've been trying it with `Thing` now, but I'm having the same issue – upon editing, it seeks `.there_is_another`.

```yml
metadata:
  title: Table for dictionary
---
variable name: "income"
data:
  employment:
    object: Thing
    model: docassemble.base.util
    item:
      name:
        object: Name
        model: docassemble.base.util
        item:
          text: "First"
      a: True
      b: 10
  business:
    object: Thing
    model: docassemble.base.util
    item:
      name:
        object: Name
        model: docassemble.base.util
        item:
          text: "Second"
      a: True
      b: 10
  recreation:
    object: Thing
    model: docassemble.base.util
    item:
      name:
        object: Name
        model: docassemble.base.util
        item:
          text: "Third"
      a: True
      b: 10
use objects: objects
gathered: True
---
code: |
  income.set_object_type(Thing)
mandatory: True
---
table: income.table
rows: income
columns:
  - Type: row_index
  - A: row_item.a
edit:
  - a
---
mandatory: True
question: |
  Summary of income
subquestion: |
  ${ income.table }
  
  ${ income.add_action() }
---
question: |
  Add another income?
yesno: income.there_is_another
---
question: |
  Income name?
fields:
  - Income: income.new_item_name
---
question: |
  A?
yesno: income[i].a
---
```

However, it is not specific for `DADict`, the following example with a `DAList` exhibits the same behavior:

```yml
variable name: "test"
data:
  object: Thing
  module: docassemble.base.util
  items:
    - name:
        object: Name
        module: docassemble.base.util
        item:
          text: "First"
      a: 2
      b: 4
    - name:
        object: Name
        module: docassemble.base.util
        item:
          text: "Second"
      a: 2
      b: 4
use objects: objects
---
mandatory: True
code: |
  test.set_object_type(Thing)
---
table: test.table
rows: test
columns:
  - A: row_item.a
  - B: row_item.b
edit:
  - a
  - b
---
question: |
  What is A?
fields:
  - A: test[i].a
    datatype: number
---
question: |
  What is the square of ${ test[i].a }?
fields:
  - B: test[i].b
    datatype: number
depends on:
  - test.a
---
code: |
  test[i].c = test[i].a + test[i].b
depends on:
  - test[i].a
  - test[i].b
---
mandatory: True
question: Table
subquestion: |
  ${ test.table }
```
