### ISSUE TITLE
`code` with `depends on` does not update multiple objects at the same time for `list collect`

### ISSUE THREAD

**Issue by fkohrt** [jhpyle/docassemble#811]
If I have a table displaying a `DAList` of `Thing`s (with properties `a` and `b`), I can automatically update `b` if `a` changes:

```yml
variable name: "test"
data:
  object: Thing
  module: docassemble.base.util
  items:
    - name:
        object: Name
        module: docassemble.base.util
        item:
          text: "First"
      a: 2
      b: 4
      c: 6
    - name:
        object: Name
        module: docassemble.base.util
        item:
          text: "Second"
      a: 2
      b: 4
      c: 6
use objects: objects
---
mandatory: True
code: |
  test.set_object_type(Thing)
  test.there_is_another = False
---
table: test.table
rows: test
columns:
  - A: row_item.a
  - B: row_item.b
edit:
  - a
  - b
---
question: |
  What is A?
fields:
  - A: test[i].a
    datatype: number
---
code: |
  test[i].b = test[i].a
depends on:
  - test[i].a
---
mandatory: True
question: Table
subquestion: |
  ${ test.table }
```

However, if I use `list collect: True` to update the property `a` of multiple objects at the same time, only one `b` is updated:

```yml
variable name: "test"
data:
  object: Thing
  module: docassemble.base.util
  items:
    - name:
        object: Name
        module: docassemble.base.util
        item:
          text: "First"
      a: 2
      b: 4
      c: 6
    - name:
        object: Name
        module: docassemble.base.util
        item:
          text: "Second"
      a: 2
      b: 4
      c: 6
use objects: objects
---
mandatory: True
code: |
  test.set_object_type(Thing)
  test.there_is_another = False
---
table: test.table
rows: test
columns:
  - A: row_item.a
  - B: row_item.b
edit:
  - a
  - b
---
question: |
  What is A?
fields:
  - A: test[i].a
    datatype: number
list collect: True
---
code: |
  test[i].b = test[i].a
depends on:
  - test[i].a
---
mandatory: True
question: Table
subquestion: |
  ${ test.table }
```
