### ISSUE TITLE
`verbatim()` content not rendered in RTF/DOCX documents

### ISSUE THREAD

**Issue by fkohrt** [jhpyle/docassemble#827]
For the following interview:

```yml
mandatory: True
question: Your document is ready.
attachments:
  - valid formats:
      - rtf
      - rtf to docx
      - pdf
      - tex
      - md
    content: |
      ${ verbatim("This is verbatim") }

      ${ plain("This is plain") }
```

Only "This is plain" appears in RTF/DOCX documents. This seems like a bug to me.
